"""
evaluate_model.py — Deepfake Detection Benchmark
======================================================
Comprehensive evaluation pipeline for 4 CNN architectures.
Follows the official FaceForensics++ testing protocol.

Key Features:
  - Dynamic input sizing based on model architecture
  - Hardware warm-up for accurate inference time tracking
  - Automated visualization generation (ROC, CM, Efficiency)
"""

import os
import sys
import json
import time
import logging
import warnings

# Suppress TensorFlow verbose logs for clean terminal output
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
warnings.filterwarnings("ignore")
logging.getLogger("tensorflow").setLevel(logging.ERROR)

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix, roc_curve,
)

# ==========================================
# CONFIGURATION
# ==========================================
DATA_DIR    = "dataset_split/test"
MODEL_DIR   = "."  # Assuming .h5 models are saved in the root directory
RESULTS_DIR = "assets"

BATCH_SIZE  = 32

# Architecture-specific input sizes (Crucial for fair comparison)
MODEL_INPUT_SIZE = {
    "Xception":    (299, 299),
    "ResNet50":    (224, 224),
    "MobileNetV2": (224, 224),
    "MesoNet4":    (256, 256),
}

# Matching the exact filenames generated by our training scripts
MODEL_FILES = {
    "Xception":    "best_xception_model.h5",
    "ResNet50":    "best_resnet50_model.h5",
    "MobileNetV2": "best_mobilenet_model.h5",
    "MesoNet4":    "best_mesonet_model.h5",
}

COLORS = ["#4C72B0", "#DD8452", "#55A868", "#C44E52"]

os.makedirs(RESULTS_DIR, exist_ok=True)

# ==========================================
# PATH VALIDATION
# ==========================================
def validate_paths():
    print("\n[SYSTEM] Validating paths...")
    all_ok = True

    for label in ["fake", "real"]:
        folder = os.path.join(DATA_DIR, label)
        if os.path.exists(folder):
            count = len([f for f in os.listdir(folder) if f.lower().endswith((".jpg", ".jpeg", ".png"))])
            print(f"  [OK] {DATA_DIR}/{label}: {count:,} images found")
            if count == 0:
                print(f"  [WARN] Folder is empty!")
                all_ok = False
        else:
            print(f"  [MISSING] {DATA_DIR}/{label}/")
            all_ok = False

    for name, fname in MODEL_FILES.items():
        path = os.path.join(MODEL_DIR, fname)
        if os.path.exists(path):
            size_mb = os.path.getsize(path) / (1024 * 1024)
            print(f"  [OK] {fname} ({size_mb:.1f} MB)")
        else:
            print(f"  [MISSING] {fname}")
            all_ok = False

    if not all_ok:
        print("\n[ERROR] Required files or directories are missing. Please complete training first.")
        sys.exit(1)

# ==========================================
# DATA GENERATOR (DYNAMIC)
# ==========================================
def build_test_generator(model_name):
    img_size = MODEL_INPUT_SIZE[model_name]
    gen = ImageDataGenerator(rescale=1.0 / 255)

    test_data = gen.flow_from_directory(
        DATA_DIR,
        target_size=img_size,
        batch_size=BATCH_SIZE,
        class_mode="binary",
        shuffle=False,
    )
    print(f"  Target Resolution : {img_size}")
    return test_data

# ==========================================
# EVALUATION CORE
# ==========================================
def evaluate_model(model_name, model_path):
    print(f"\n{'-'*50}\n  Evaluating: {model_name}\n{'-'*50}")

    model = load_model(model_path)
    test_data = build_test_generator(model_name)

    # Hardware Warm-up for accurate inference timing
    img_size = MODEL_INPUT_SIZE[model_name]
    dummy = np.zeros((1, *img_size, 3), dtype=np.float32)
    model.predict(dummy, verbose=0)

    # Inference Execution
    test_data.reset()
    y_true = test_data.classes.copy()

    t_start = time.time()
    y_pred_prob = model.predict(test_data, verbose=0).flatten()
    t_elapsed = time.time() - t_start
    inference_ms = round((t_elapsed / len(y_true)) * 1000, 3)

    y_pred = (y_pred_prob >= 0.5).astype(int)

    # Align predictions (Ensure 'fake' is the positive class)
    class_indices = test_data.class_indices
    if class_indices.get("fake") == 0:
        y_true_eval = 1 - y_true
        y_pred_eval = 1 - y_pred
        y_prob_eval = 1 - y_pred_prob
    else:
        y_true_eval = y_true
        y_pred_eval = y_pred
        y_prob_eval = y_pred_prob

    # Metrics Calculation
    acc = float(accuracy_score(y_true_eval, y_pred_eval))
    precision = float(precision_score(y_true_eval, y_pred_eval, zero_division=0))
    recall = float(recall_score(y_true_eval, y_pred_eval, zero_division=0))
    f1 = float(f1_score(y_true_eval, y_pred_eval, zero_division=0))
    auc = float(roc_auc_score(y_true_eval, y_prob_eval))
    cm = confusion_matrix(y_true_eval, y_pred_eval)
    fpr, tpr, _ = roc_curve(y_true_eval, y_prob_eval)

    print(f"  Accuracy   : {acc:.4f}")
    print(f"  F1-Score   : {f1:.4f}")
    print(f"  AUC-ROC    : {auc:.4f}")
    print(f"  Speed      : {inference_ms:.2f} ms/frame")

    tf.keras.backend.clear_session()

    return {
        "model": model_name,
        "accuracy": round(acc, 4),
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1_score": round(f1, 4),
        "auc_roc": round(auc, 4),
        "inference_ms": inference_ms,
        "total_params": int(model.count_params()),
        "n_samples": int(len(y_true)),
        "confusion_matrix": cm.tolist(),
        "roc_fpr": fpr.tolist(),
        "roc_tpr": tpr.tolist(),
    }

# ==========================================
# VISUALIZATION MODULES
# ==========================================
def plot_comparison_metrics(results):
    df = pd.DataFrame(results)
    metrics = ["accuracy", "precision", "recall", "f1_score", "auc_roc"]
    labels = ["Accuracy", "Precision", "Recall", "F1-Score", "AUC-ROC"]

    fig, axes = plt.subplots(1, 5, figsize=(20, 5))
    fig.suptitle("Deepfake Detection: Model Performance Benchmarking", fontsize=14, fontweight="bold", y=1.05)

    for ax, metric, label in zip(axes, metrics, labels):
        vals = df[metric].values
        bars = ax.bar(df["model"], vals, color=COLORS[:len(vals)], edgecolor="white", linewidth=0.8)
        ax.set_title(label, fontsize=12, fontweight="bold")
        ax.set_ylim(0, 1.15)
        ax.set_xticklabels(df["model"], rotation=30, ha="right", fontsize=9)
        ax.grid(axis="y", linestyle="--", alpha=0.4)
        for bar, val in zip(bars, vals):
            ax.text(bar.get_x() + bar.get_width()/2, val + 0.02, f"{val:.3f}", ha="center", va="bottom", fontsize=9)

    plt.tight_layout()
    plt.savefig(os.path.join(RESULTS_DIR, "benchmark_metrics.png"), dpi=150, bbox_inches="tight")
    plt.close()

def plot_confusion_matrices(results):
    n = len(results)
    rows = (n + 1) // 2
    fig, axes = plt.subplots(rows, 2, figsize=(12, 5 * rows))
    fig.suptitle("Confusion Matrices (Positive Class = Fake)", fontsize=14, fontweight="bold")
    axes = axes.flatten()

    for i, res in enumerate(results):
        cm = np.array(res["confusion_matrix"])
        sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=["Real", "Fake"], yticklabels=["Real", "Fake"], ax=axes[i], cbar=False, annot_kws={"size": 14, "weight": "bold"})
        axes[i].set_title(f"{res['model']} (AUC={res['auc_roc']:.3f})", fontsize=12)
        axes[i].set_xlabel("Predicted")
        axes[i].set_ylabel("Actual")

    for j in range(n, len(axes)): axes[j].set_visible(False)
    plt.tight_layout(pad=2.5)
    plt.savefig(os.path.join(RESULTS_DIR, "confusion_matrices.png"), dpi=150, bbox_inches="tight")
    plt.close()

def plot_roc_curves(results):
    fig, ax = plt.subplots(figsize=(8, 7))
    for res, color in zip(results, COLORS):
        ax.plot(res["roc_fpr"], res["roc_tpr"], color=color, lw=2.5, label=f"{res['model']} (AUC={res['auc_roc']:.3f})")

    ax.plot([0,1], [0,1], "k--", lw=1.5, label="Random Guess", alpha=0.6)
    ax.set_xlim([0, 1]); ax.set_ylim([0, 1.05])
    ax.set_xlabel("False Positive Rate", fontsize=12)
    ax.set_ylabel("True Positive Rate", fontsize=12)
    ax.set_title("ROC Curve Analysis", fontsize=14, fontweight="bold")
    ax.legend(loc="lower right")
    ax.grid(linestyle="--", alpha=0.4)

    plt.savefig(os.path.join(RESULTS_DIR, "roc_curves.png"), dpi=150, bbox_inches="tight")
    plt.close()

def save_report(results):
    rows = [{
        "Model": r["model"],
        "Accuracy": r["accuracy"],
        "F1-Score": r["f1_score"],
        "AUC-ROC": r["auc_roc"],
        "Inference_ms": r["inference_ms"],
        "Parameters": r["total_params"],
    } for r in results]
    df = pd.DataFrame(rows)
    df.to_csv(os.path.join(RESULTS_DIR, "benchmark_report.csv"), index=False)
    
    with open(os.path.join(RESULTS_DIR, "benchmark_report.json"), "w") as f:
        json.dump([{k: v for k, v in r.items() if not k.startswith("roc_")} for r in results], f, indent=2)
    return df

# ==========================================
# MAIN EXECUTION
# ==========================================
def main():
    print("============================================================")
    print(" INITIATING DEEPFAKE MODEL BENCHMARKING")
    print("============================================================")
    validate_paths()

    results = []
    for model_name, model_file in MODEL_FILES.items():
        try:
            results.append(evaluate_model(model_name, os.path.join(MODEL_DIR, model_file)))
        except Exception as e:
            print(f"  [ERROR] Skipping {model_name}: {e}")

    if not results:
        print("\n[ERROR] No models successfully evaluated.")
        return

    print("\n[PROCESS] Generating architectural visualizations...")
    plot_comparison_metrics(results)
    plot_confusion_matrices(results)
    plot_roc_curves(results)
    df = save_report(results)

    print("\n============================================================")
    print(" FINAL RANKING (BY AUC-ROC)")
    print("============================================================")
    ranked = df.sort_values("AUC-ROC", ascending=False).reset_index(drop=True)
    print(ranked.to_string(index=False))
    print(f"\n[SUCCESS] All benchmark assets saved to: {os.path.abspath(RESULTS_DIR)}/")

if __name__ == "__main__":
    main()